### ISSUE TITLE
flutter_svg depends on min. Flutter SDK 1.18.0-6.0.pre 

### ISSUE THREAD

**Issue by AndroidNils** [dnfield/flutter_svg#361]
Why is flutter_svg depending on min. Flutter SDK 1.18.0-6.0.pre? Because of it, flutter_svg is hidden on DartPad. 

![image](https://user-images.githubusercontent.com/24459435/84140454-f2c08e80-aa51-11ea-82ee-70612deebd96.png)

![image](https://user-images.githubusercontent.com/24459435/84140583-23a0c380-aa52-11ea-8eae-bdbf05927ac1.png)

**Comment by rydancerrr** [comment]
Same issue. I tried to upgrade my flutter sdk but I already have the latest version. 

![image](https://user-images.githubusercontent.com/46836118/84571090-d0b56c00-adc3-11ea-8ee2-9f30975d6bfc.png)

**Comment by Emex4gman** [comment]
@rohanchandra your suggestion worked for me

**Comment by AndroidNils** [comment]
I created a PR, which should solve this problem: #363

```
flutter_svg:
  git:
    url: https://github.com/AndroidNils/flutter_svg.git
    ref: patch-1
```
