### ISSUE TITLE
The "pub get" doesn't get the package

### ISSUE THREAD

**Issue by northonBarbosa** [dnfield/flutter_svg#404]
Hey, I'm addin the package dependecy on pubspec file but it's returning me an error:

[app_flutter] flutter pub get
Running "flutter pub get" in app_flutter...               
Because no versions of flutter_svg match 0.18.0 and no versions of flutter_svg match >0.18.0 <0.19.0, flutter_svg ^0.18.0 is forbidden.

So, because app_flutter depends on flutter_svg ^0.18.0, version solving failed.
pub get failed (1; So, because vistorias_flutter depends on flutter_svg ^0.18.0, version solving failed.)
exit code 1

Can anyone help me?

**Comment by dnfield** [comment]
https://pub.dev/packages/flutter_svg shows v0.18.0.

Please share a full pubspec, or a git repo that reproduces this issue.

**Comment by northonBarbosa** [comment]
```
name: app_flutter
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_svg: ^0.18.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
  uses-material-design: true`

```
That's the full code from pubspec
