### ISSUE TITLE
'package:flutter_svg/src/cache.dart': Failed assertion: line 103 pos 14: '_cache.containsKey(key) || _cache.length < maximumSize': is not true.

### ISSUE THREAD

**Issue by vpohrebniakov** [dnfield/flutter_svg#883]
**flutter_svg: ^2.0.3**

**sdk: ">=2.17.6 <3.0.0"
  flutter: 3.7.7**

I have a list of items with svg icons. And when I'm scrolling this list I see errors in logs:

```
flutter: 'package:flutter_svg/src/cache.dart': Failed assertion: line 103 pos 14: '_cache.containsKey(key) || _cache.length < maximumSize': is not true.
flutter: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      Cache._add (package:flutter_svg/src/cache.dart:103:14)
#3      Cache.putIfAbsent.<anonymous closure> (package:flutter_svg/src/cache.dart:89:9)
#4      _rootRunUnary (dart:async/zone.dart:1406:47)
<asynchronous suspension>
```

Maybe it's similar to https://github.com/dnfield/flutter_svg/issues/863, but I'm not sure.

**Comment by Albert221** [comment]
I have the same error on `2.0.3`.

@dnfield I see you already fixed this error in #879, but this assert still fires.

Isn't it some race condition that's happening when I'm loading many SVGs asynchronically?

**Comment by dnfield** [comment]
Can you share a reproduction case?

**Comment by Albert221** [comment]
```yaml
# pubspec.yaml
name: flutter_svg_issue_883
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: 2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
```

```dart
// main.dart
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';

void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        appBar: AppBar(),
        body: GridView.count(
          crossAxisCount: 4,
          children: List.generate(
            200,
            (index) => SvgPicture.asset('assets/$index.svg'),
          ),
        ),
      ),
    ),
  );
}
```

`assets/0.svg` - https://upload.wikimedia.org/wikipedia/commons/a/a0/Circle_-_black_simple.svg

Then run this in `assets/` to duplicate it `for i in {1..200}; do cp 0.svg "$i.svg"; done`

Run the app and scroll fast
